name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run ktlint check
        run: bash ./gradlew ktlintCheck